main: at.boing.jsplugins.MainPlugin
name: JSPlugins
version: Alpha

commands:
  js:
    description: Performs an action on javascript plugins
    usage: /<command> [task]
    permission: <plugin name>.basic
    permission-message: You don't have <permission>